### ISSUE TITLE
Erro ao utilizar função codBarras2LinhaDigitavel

### ISSUE THREAD

**Issue by rafaelji** [mrmgomes/boleto-utils#4]
Olá, primeiramente parabéns e obrigado pelo esforço em desenvolver essa solução!
fui utilizar sua lib e estou enfrentando um problema após importar a função que converte código de barras em linha digitavel.
```
import { codBarras2LinhaDigitavel }  from "@mrmgomes/boleto-utils";

codBarras2LinhaDigitavel(codigo, false);
```

O retorno é:

`[TypeError: undefined is not an object (evaluating '_this.identificarTipoBoleto')]`

**Comment by mrmgomes** [comment]
> Olá, primeiramente parabéns e obrigado pelo esforço em desenvolver essa solução!
> fui utilizar sua lib e estou enfrentando um problema após importar a função que converte código de barras em linha digitavel.
> 
> ```
> import { codBarras2LinhaDigitavel }  from "@mrmgomes/boleto-utils";
> 
> codBarras2LinhaDigitavel(codigo, false);
> ```
> 
> O retorno é:
> 
> `[TypeError: undefined is not an object (evaluating '_this.identificarTipoBoleto')]`

Obrigado, Rafael! A solução está longe de estar perfeita, mas vamos tentando! :-)

Verifiquei aqui e a função codBarras2LinhaDigitavel() está retornando o valor esperado. Você tá usando a versão mais recente (1.2.0)?

Tem como você passar mais informações? O que essa função `identificarTipoBoleto` faz?

**Comment by rafaelji** [comment]
Obrigado por responder minha dúvida!

> Tem como você passar mais informações? O que essa função identificarTipoBoleto faz?

Essa função não é minha, na verdade ela é chamada dentro da função `codBarras2LinhaDigitavel()` no arquivo `node_modules/@mrmgomes/boleto-utils/src/boleto-utils.js` na linha `298`.

Estou usando sua lib num projeto feito com React Native, porém acredito que isso não influenciaria em nada pois estou importando uma lib javascript normalmente (não tem influência da parte nativa).

As informações que eu passei ajudaram?

**Comment by mrmgomes** [comment]
Ah ok, achei que você estivesse chamando a sua própria função.
De qualquer forma, realizei todos os testes aqui. Até inclui 3 novos testes unitários (com Mocha e Chai) pra validar o uso da função `codBarras2LinhaDigitavel()` e o resultado foi positivo.

![Captura de Tela 2020-09-10 às 15 08 59](https://user-images.githubusercontent.com/476030/92778455-92562b80-f377-11ea-9db1-3597f42faa8c.png)

Creio que o problema esteja a forma que você está chamando a função em seu código e não na lib.
De qualquer forma, assegure-se de usar a versão mais recente: 1.2.0.

**Comment by rafaelji** [comment]
Olá novamente, cara estou chamando exatamente como mostrei ali no primeiro comentário

```
import { codBarras2LinhaDigitavel }  from "@mrmgomes/boleto-utils";

codBarras2LinhaDigitavel(codigo, false);
```
e não está indo. Eu testei sua lib no RunKit do npm (utilizando require pois lá não suporta import do ES6) e funcionou. Infelizmente no meu ambiente não está indo. Você utiliza ela como? Pode me mostrar um exemplo prático dela funcionando com import do ES6 por favor?

**Comment by mrmgomes** [comment]
> Olá novamente, cara estou chamando exatamente como mostrei ali no primeiro comentário
> 
> ```
> import { codBarras2LinhaDigitavel }  from "@mrmgomes/boleto-utils";
> 
> codBarras2LinhaDigitavel(codigo, false);
> ```
> 
> e não está indo. Eu testei sua lib no RunKit do npm (utilizando require pois lá não suporta import do ES6) e funcionou. Infelizmente no meu ambiente não está indo. Você utiliza ela como? Pode me mostrar um exemplo prático dela funcionando com import do ES6 por favor?

Claro!

Segue o código:

`import { codBarras2LinhaDigitavel }  from '@mrmgomes/boleto-utils';`

`const codBarras = '85820000000572503282035607082021053959190446'`
`function converterBarras2Linha(codBarras) {
    return codBarras2LinhaDigitavel(codBarras, false);
}`
`console.log('converterBarras2Linha() :>> ', converterBarras2Linha(codBarras));`

E o resultado:
![Captura de Tela 2020-09-15 às 10 02 53](https://user-images.githubusercontent.com/476030/93213810-b8dee280-f73a-11ea-919b-2b1e91fa7722.png)

**Comment by rafaelji** [comment]
Bom, o problema é só comigo então. Vou fechar a issue, obrigado por responder! abraço.

**Comment by WeslleyNasRocha** [comment]
Sei que essa issue é antigassa, mas tambem n consegui usar no react native e fiz [um port](https://www.npmjs.com/package/@weslleyrocha/boleto-utils) com typescript e tsup, agora funciona
